linux-system-roles/ssh

README.md
This was caused by removing some of the variables from public-facing documentation
=> README: Fix ssh_drop_in_name option description

.github/workflows/ansible-debian.yml, .github/workflows/ansible-ubuntu.yml, tasks/main.yml, tasks/set_vars.yml, tests/setup-snapshot.yml, tests/tests_default.yml, vars/main.yml
Some users use `gather_facts: false` in their playbooks.  This changes
the role to work in that case, by gathering only the facts it requires
to run.
CI testing can be sped up by creating a snapshot image pre-installed
with packages.  tests/setup-snapshot.yml can be used by a CI system
to do this.
=> support gather_facts: false; support setup-snapshot.yml (#71)

.github/workflows/ansible-ubuntu.yml, README.md, meta/main.yml
The PRs for CI are already merged so revert back to the upstream version of the actions. Update also relevancy in meta, readme and ads CI badges.
=> Update CI and docs

CHANGELOG.md
[1.1.8] - 2022-07-19
--------------------
- none
- none
- make all tests work with gather_facts: false (#39)
Ensure that all of the tests work when using ANSIBLE_GATHERING=explicit
- make min_ansible_version a string in meta/main.yml (#40)
The Ansible developers say that `min_ansible_version` in meta/main.yml
must be a `string` value like `"2.9"`, not a `float` value like `2.9`.
- Add CHANGELOG.md (#41)
=> Version 1.1.8 - CHANGELOG.md [citest skip]

templates/ssh_config.j2
Some versions of jinja will not automatically convert values to
string in a `{{ ... }}` block, so use `| string` to ensure that
it is converted to string.
=> cast value to string in jinja macro

CHANGELOG.md
[1.1.11] - 2022-09-27
--------------------
- Add final version of the option RequiredRSASize (#53)
Update source template to match generated template
Add final name of the RequiredRSASize parameter
keeping the old version for backward compatibility.
Upstream commit:
https://github.com/openssh/openssh-portable/commit/54b333d1
- none
- none
=> Version 1.1.11 - CHANGELOG.md [citest skip]

.dev-tools/10_top.j2, templates/ssh_config.j2
Add role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by System Roles. It may also be used for future analysis.
=> Fingerprint RHEL System Role managed config files

vars/Rocky_8.yml, vars/Rocky_9.yml
Currently no `vars` file is picked up in the task `ssh : Set platform/version specific variables` when running against `Rocky8` or `Rocky9`.
This is fixed by creating the softlinks:
```txt
Rocky_8.yml -> RedHat_8.yml
Rocky_9.yml -> RedHat_9.yml
``` 
Another approach would be to simplify `set_vars.yml` by doing somehting similar to `willshersystems.sshd`, the relevant code is here: <https://github.com/willshersystems/ansible-sshd/blob/master/tasks/variables.yml#L8-L33>. This would allow us to get rid of the many softlinks for RHEL derivatives.
=> add vars files for Rocky 8/9

.dev-tools/10_top.j2, templates/ssh_config.j2
Only the first list item was properly indented. In case of the RHEL7 default config the indent was like
```config
#
#
Host *
ForwardX11Trusted yes
GSSAPIAuthentication yes
SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
SendEnv XMODIFIERS
```
this is now fixed. I.e. the default results in 
```config
#
#
Host *
ForwardX11Trusted yes
GSSAPIAuthentication yes
SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
SendEnv XMODIFIERS
```
=> Proper indent when lists are used in block

tests/tests_user_config.yml
ansible-lint now requires the use of changed_when even for
conditional tasks
=> ansible-lint - use changed_when for conditional tasks

.github/workflows/commitlint.yml
For more information, see Conventional Commits format in Contribute
https://linux-system-roles.github.io/contribute.html#conventional-commits-format
Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>
=> ci: Add commitlint GitHub action to ensure conventional commits

.github/workflows/ansible-debian.yml
This debian version went EOL last year and now fails most of the time. Described in the following issue:
https://github.com/roles-ansible/check-ansible-debian-stretch-action/issues/2
=> ci: Remove Debian stretch (9)

tasks/main.yml
Enhancement:
Reason: Forbidden implicit octal value "0700" was found on line 21.
Result: Updated to use explicit octal format for better readability and to adhere to linting standards.
Issue Tracker Tickets (Jira or BZ if any):na
=> ci: Fix implicit octal value in main.yml

tests/tasks/backup.yml, tests/tasks/restore.yml
I noticed some test failures in tests that check ownership/permissions
of config files.  The tests were recently changed to reuse the same
VM, so I suspect config files were not being backed up/restored with
the correct file attributes.  Use `cp -a` to preserve all file
attributes.
=> tests: Ensure backup/restore preserves file attributes

.ansible-lint, .ostree/README.md, .ostree/get_ostree_data.sh, .ostree/packages-runtime.txt, .ostree/packages-testing-CentOS-7.txt, .ostree/packages-testing-CentOS-8.txt, .ostree/packages-testing-CentOS-9.txt, .ostree/packages-testing-Fedora.txt, .ostree/packages-testing-RedHat-7.txt, .ostree/packages-testing-RedHat-8.txt, .ostree/packages-testing-RedHat-9.txt, .sanity-ansible-ignore-2.12.txt, .sanity-ansible-ignore-2.13.txt, .sanity-ansible-ignore-2.14.txt, .sanity-ansible-ignore-2.15.txt, .sanity-ansible-ignore-2.9.txt, README-ostree.md, README.md, meta/collection-requirements.yml, tasks/set_vars.yml, tests/tasks/setup.yml, tests/tests_all_options.yml
Feature: Allow running and testing the role with ostree managed nodes.
Reason: We have users who want to use the role to manage ostree
systems.
Result: Users can use the role to manage ostree managed nodes.
=> feat: support for ostree systems

.ostree/get_ostree_data.sh
Use the `#!/usr/bin/env bash` shebang which is ansible-test friendly.
This means we can remove get_ostree_data.sh from the .sanity* files.
This also means we can remove the .sanity* files if we do not need
them otherwise.
Rename `pth` to `path` in honor of nscott
=> refactor: get_ostree_data.sh use env shebang - remove from .sanity*

tests/tests_additional_packages.yml, tests/tests_all_options.yml, tests/tests_no_skip_defaults.yml
Enhancement: Fix wrong assert in test
Reason: The assert was wrong causing warning and test failures on Debian
Result: The assert was fixed
Issue Tracker Tickets (Jira or BZ if any): -
=> fix: Fix warning for using jinja templates in assert

vars/ALP-Dolomite.yml
Enhancement: Add variables for additional operating system.
Reason: The existing configuration does not cover [SUSE ALP](https://documentation.suse.com/alp/dolomite/html/alp-dolomite/index.html), the default configurations are being used.
Result: Works as expected in the added operating system.
Issue Tracker Tickets (Jira or BZ if any):na
=> ci: Add ALP-Dolomite var file

.dev-tools/options_body, .github/workflows/ansible-centos.yml, .github/workflows/ansible-fedora.yml, tasks/main.yml, templates/ssh_config.j2, tests/tests_all_options.yml, tests/tests_user_config.yml
Enhancement: Run tests on Fedora and CentOS
Reason: The downstream testing is down-sizing and moving upstream
Result: We are able to catch issues earlier in upstream.
Issue Tracker Tickets (Jira or BZ if any): -
=> ci: Run Fedora/CentOS CI in GH Actions + unbreak debian buster CI run

.dev-tools/options_body, templates/ssh_config.j2, tests/tests_all_options.yml
Enhancement: Add new configuration options  `ObscureKeystrokeTiming` and `ChannelTimeout`; remove false positives in the test
Reason: New OpenSSH was released with new configuration option.
Result: The option is recognized by the system role.
Issue Tracker Tickets (Jira or BZ if any): -
=> feat: Add new configuration options and remove false positives in the test

.ostree/packages-testing-CentOS-10.txt, .ostree/packages-testing-CentOS-7.txt, .ostree/packages-testing-CentOS-8.txt, .ostree/packages-testing-CentOS-9.txt, .ostree/packages-testing-RedHat-10.txt, meta/main.yml, vars/CentOS_10.yml, vars/RedHat_10.yml
According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …
=> fix: add support for EL10

tests/vars/rh_distros_vars.yml, vars/AlmaLinux_10.yml, vars/AlmaLinux_8.yml, vars/AlmaLinux_9.yml, vars/Rocky_10.yml, vars/main.yml
We have a lot of requests to support Rocky and Alma in various system roles. The
first part of adding support is adding `vars/` files for these platforms. In
almost every case, for a given major version N, the vars file RedHat_N.yml can
be used for CentOS, Rocky, and Alma.  Rather than making a copy of the
RedHat_N.yml file, just use a symlink to reduce size and maintenance burden, and
standardize this across all system roles for consistency.
NOTE: There is no Alma or Rocky version 7 or less.
NOTE: OracleLinux is not a strict clone, so we are not going to do this for
OracleLinux at this time.  Support for OracleLinux will need to be done in
separate PRs. For more information, see
https://github.com/linux-system-roles/cockpit/issues/130
**Question**: Why not just use …
=> refactor: Use vars/RedHat_N.yml symlink for CentOS, Rocky, Alma wherever possible

.github/workflows/ansible-centos.yml, README.md, tests/tests_match.yml
Enhancement: Fix tests in CentOS 10 and add GH based tests to CI
Reason: The OpenSSH broke parsing of Compression option
Result: The tests were failing
Issue Tracker Tickets (Jira or BZ if any): RHEL-68346
=> fix: Workaround for CentOS 10 issues in openssh

.README.html, CHANGELOG.md
Update changelog and .README.html for version 1.5.2
=> docs(changelog): version 1.5.2 [citest skip]

.ostree/packages-testing-Fedora.txt, .ostree/packages-testing-RedHat-10.txt, .ostree/packages-testing-RedHat-7.txt, .ostree/packages-testing-RedHat-8.txt, .ostree/packages-testing-RedHat-9.txt, .ostree/packages-testing.txt, tests/tests_all_options.yml
Enhancement: Add missing dependency
Reason: Fedora removed awk from the minimal containers, which caused some tests to fail.
Result: Added awk installation to the test. 
Issue Tracker Tickets (Jira or BZ if any): -
=> tests: Add missing dependency on Fedora 42
